import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import "./globals.css";
import LoginBtn from "./LoginBtn.js"; //1. import

import Link from "next/link";
import NextAuthProvider from "./SessionProvider";
import LogoutBtn from "./LogoutBtn";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions); //1-1

  console.log(JSON.stringify(session));

  return (
    <html lang="en">
      <body>
        <NextAuthProvider session={session}>
          <div className="navbar">
            <Link href="/" className="logo">
              BSSM board
            </Link>
            <Link href="/list">글목록</Link>
            <Link href="/write">글작성</Link>
            {session ? (
              <span style={{ color: "black" }}>
                {session.user.name} <LogoutBtn />{" "}
              </span>
            ) : (
              <LoginBtn />
            )}
          </div>
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
